# Generated by Django 3.2.5 on 2021-07-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_ordermodel_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordermodel',
            table='food_ordermodel',
        ),
    ]
